import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  UserButton
} from '@clerk/nextjs';
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <SignedIn>
            <div className='absolute w-200 h-full bg-gray-400'>
              <UserButton
                appearance={{
                  elements: {
                    userButtonAvatarBox: 'm-2 w-12 h-12 border'
                  }
                }}
              />
              <div
                className="m-2"
              >
                <Link
                  className="text-white bg-blue-500 p-2 rounded"
                  href={'/dashboard'}
                >Dashboard</Link>
              </div>
            </div>
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
